# Generated by Django 4.2.5 on 2023-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_section_name",
                    models.CharField(max_length=50, verbose_name="Название раздела"),
                ),
                ("site_section_slug", models.SlugField(verbose_name="Слаг")),
                (
                    "link_to_section_page",
                    models.URLField(verbose_name="Ссылка на страницу раздела"),
                ),
                (
                    "site_section_icon",
                    models.ImageField(
                        upload_to="icons/", verbose_name="Иконка раздела"
                    ),
                ),
                (
                    "output_order",
                    models.IntegerField(
                        unique=True, verbose_name="Порядок вывода в списке разделов"
                    ),
                ),
                (
                    "section_is_active",
                    models.BooleanField(
                        default=False,
                        verbose_name="Признак отображения на главной странице",
                    ),
                ),
            ],
        ),
    ]
